"""Emit firmware/include/mapping.h from the same spiral geometry the PCB is laid out from.

The board is a Fermat spiral: LED n sits at radius LED_SPACING*sqrt(n) and angle
n*137.508 degrees, and LED_MAP is the order the chain visits those positions (21 strips
of 3, every other one reversed). mapping.py prints the normalized x/y for
led_config.cpp; this emits the same numbers plus the polar pair the effects want, so no
sqrt/atan2 runs per pixel per frame.

    cd lolly_pcb && python3 emit_firmware_mapping.py > ../firmware/include/mapping.h
"""

import math

LED_SPACING = 5.5
LEDS = 63
GOLDEN_ANGLE_DEG = 137.508

# Chain order: strip index -> the first LED of that strip, then every 21st after it.
STRIP_STARTS = [1, 9, 17, 4, 12, 20, 7, 15, 2, 10, 18, 5, 13, 21, 8, 16, 3, 11, 19, 6, 14]


def chain_order():
    """Spiral index (1-based) of each LED, in the order the data line reaches them."""
    order = []
    for stripidx, j in enumerate(STRIP_STARTS):
        strip = list(range(j, LEDS + 1, 21))
        if stripidx % 2 == 1:
            strip.reverse()
        order += strip
    return order


def positions():
    """Normalized (x, y) per chain index, identical to mapping.py's output."""
    order = chain_order()
    raw = []
    for led_idx in range(1, LEDS + 1):
        n = order[led_idx - 1]
        r = LED_SPACING * math.sqrt(n)
        angle = (n * GOLDEN_ANGLE_DEG / 180) * math.pi
        raw.append((r * math.cos(angle), r * math.sin(angle)))

    # Same divider as mapping.py: the larger half-extent, so the wider axis lands on 1.0.
    divider = max(max(abs(x) for x, _ in raw), max(abs(y) for _, y in raw))
    return [(x / divider, y / divider) for x, y in raw]


def rows(values, per_line=6):
    out = []
    for i in range(0, len(values), per_line):
        out.append("  " + " ".join(f"{v:.6f}f," for v in values[i:i + per_line]))
    return "\n".join(out).rstrip(",")


def int_rows(values, per_line=12):
    out = []
    for i in range(0, len(values), per_line):
        out.append("  " + " ".join(f"{v}," for v in values[i:i + per_line]))
    return "\n".join(out).rstrip(",")


def main():
    pos = positions()
    xs = [x for x, _ in pos]
    ys = [y for _, y in pos]
    radii = [math.hypot(x, y) for x, y in pos]
    # Angle as turns in [0,1) rather than radians: effects use it as a hue and as a
    # sweep coordinate, both of which want to wrap at 1.
    turns = [(math.atan2(y, x) / (2 * math.pi)) % 1.0 for x, y in pos]

    print("// GENERATED by lolly_pcb/emit_firmware_mapping.py -- DO NOT EDIT BY HAND.")
    print("// Source of truth: lolly_pcb/mapping.py (63 LEDs, Fermat spiral, golden angle).")
    print("#pragma once")
    print("#include <stdint.h>")
    print()
    print("namespace Mapping {")
    print(f"  constexpr uint16_t LED_COUNT = {LEDS};")
    print(f"  // Largest radius on the board, in the same normalized units as LED_X/LED_Y.")
    print(f"  constexpr float MAX_RADIUS = {max(radii):.6f}f;")
    print()
    print("  // Centred on the spiral origin, larger half-extent -> 1.0. Same numbers the")
    print("  // simulator draws with, so an effect looks the same in both.")
    print("  constexpr float LED_X[LED_COUNT] = {")
    print(rows(xs))
    print("  };")
    print("  constexpr float LED_Y[LED_COUNT] = {")
    print(rows(ys))
    print("  };")
    print()
    print("  // Precomputed polar pair: radius in LED_X/LED_Y units, angle in turns [0,1).")
    print("  constexpr float LED_R[LED_COUNT] = {")
    print(rows(radii))
    print("  };")
    print("  constexpr float LED_THETA[LED_COUNT] = {")
    print(rows(turns))
    print("  };")
    print()
    print("  // Chain indices sorted by angle: walk this to travel once around the board.")
    print("  // The data line's own order zigzags in and out along the spiral arms, so an")
    print("  // effect that steps by chain index scatters rather than sweeping. Anything that")
    print("  // wants motion to read as going round the circle steps through this instead.")
    print("  constexpr uint8_t ANGULAR_ORDER[LED_COUNT] = {")
    print(int_rows(sorted(range(LEDS), key=lambda i: turns[i])))
    print("  };")
    print("}")


if __name__ == "__main__":
    main()
