#!/bin/sh
# Pack the simulator into include/spa_gz.h, the copy the device serves at "GET /".
# There is no filesystem partition on this board, so PROGMEM is the only place the
# page can live and a flash is the only way to update it.
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/../simulator/index.html"
HDR="$ROOT/include/spa_gz.h"

WORK="${TMPDIR:-/tmp}/mini-lolly-spa"
mkdir -p "$WORK"
FLAT="$WORK/index.flat.html"
GZ="$WORK/index.html.gz"
trap 'rm -f "$FLAT"' EXIT

# The device serves one file for "GET /" and 404s everything else, so sibling
# assets must be baked into the HTML or they never load and the SPA dies on the
# first reference.
python3 - "$SRC" "$FLAT" <<'PY'
import os, re, sys
src, dst = sys.argv[1], sys.argv[2]
html = open(src, encoding="utf-8").read()
base = os.path.dirname(src)

def read_asset(name, closer):
    path = os.path.join(base, name)
    if not os.path.isfile(path):
        sys.exit(f"error: {src} references missing {name}")
    text = open(path, encoding="utf-8").read()
    # A literal closing tag inside the asset would end the block early and leave
    # the rest of the file as page text, so refuse rather than ship a broken SPA.
    if closer in text:
        sys.exit(f"error: {name} contains a literal {closer} and cannot be inlined")
    print(f"Inlined {name} ({len(text)} bytes)")
    return text

def inline_js(m):
    return "<script>\n" + read_asset(m.group(1), "</script>") + "\n</script>"

def inline_css(m):
    return "<style>\n" + read_asset(m.group(1), "</style>") + "\n</style>"

html, ncss = re.subn(
    r'<link\s+rel="stylesheet"\s+href="([^"/:]+\.css)"\s*/?>', inline_css, html)
html, njs = re.subn(
    r'<script\s+src="([^"/:]+\.js)"\s*></script>', inline_js, html)
if not (ncss + njs):
    print("No external assets to inline")
open(dst, "w", encoding="utf-8").write(html)
PY

gzip -c -f "$FLAT" > "$GZ"
echo "Gzipped to $(wc -c < "$GZ") bytes"

python3 - "$GZ" "$HDR" <<'PY'
import sys
data = open(sys.argv[1], "rb").read()
out = open(sys.argv[2], "w")
out.write("// GENERATED by scripts/prepare_data.sh - do not edit.\n")
out.write("#pragma once\n#include <stdint.h>\n#include <pgmspace.h>\n\n")
out.write(f"static const uint32_t SPA_GZ_LEN = {len(data)};\n")
out.write("static const uint8_t SPA_GZ[] PROGMEM = {\n")
for i, b in enumerate(data):
    if i % 16 == 0:
        out.write("  ")
    out.write(f"0x{b:02x},")
    if i % 16 == 15:
        out.write("\n")
if len(data) % 16:
    out.write("\n")
out.write("};\n")
out.close()
print(f"Wrote {sys.argv[2]} ({len(data)} bytes)")
PY
